name = "sales-hub"
embedded = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
scopes = "read_products,read_customers,read_companies,write_draft_orders,read_draft_orders,read_orders"

[webhooks]
api_version = "2025-01"
